CTFd/admin/__init__.py
from flask import (
    current_app as app,
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    abort,
    render_template_string,
    send_file,
)

from CTFd.utils.decorators import admins_only
from CTFd.utils.user import is_admin
from CTFd.utils.security.auth import logout_user
from CTFd.utils import config as ctf_config, get_config, set_config
from CTFd.cache import cache, clear_config
from CTFd.utils.helpers import get_errors
from CTFd.utils.exports import (
    export_ctf as export_ctf_util,
    import_ctf as import_ctf_util,
)
from CTFd.models import (
    db,
    get_class_by_tablename,
    Users,
    Teams,
    Configs,
    Submissions,
    Solves,
    Awards,
    Unlocks,
    Tracking,
)
import datetime
import os
import six
import csv


admin = Blueprint("admin", __name__)


from CTFd.admin import challenges  # noqa: F401
from CTFd.admin import pages  # noqa: F401
from CTFd.admin import scoreboard  # noqa: F401
from CTFd.admin import statistics  # noqa: F401
from CTFd.admin import teams  # noqa: F401
from CTFd.admin import users  # noqa: F401
from CTFd.admin import submissions  # noqa: F401
from CTFd.admin import notifications  # noqa: F401


@admin.route("/admin", methods=["GET"])
def view():
    if is_admin():
        return redirect(url_for("admin.statistics"))
    return redirect(url_for("auth.login"))


@admin.route("/admin/plugins/<plugin>", methods=["GET", "POST"])
@admins_only
def plugin(plugin):
    if request.method == "GET":
        plugins_path = os.path.join(app.root_path, "plugins")

        config_html_plugins = [
            name
            for name in os.listdir(plugins_path)
            if os.path.isfile(os.path.join(plugins_path, name, "config.html"))
        ]

        if plugin in config_html_plugins:
            config_html = open(
                os.path.join(app.root_path, "plugins", plugin, "config.html")
            ).read()
            return render_template_string(config_html)
        abort(404)
    elif request.method == "POST":
        for k, v in request.form.items():
            if k == "nonce":
                continue
            set_config(k, v)
        with app.app_context():
            clear_config()
        return "1"


@admin.route("/admin/import", methods=["POST"])
@admins_only
def import_ctf():
    backup = request.files["backup"]
    errors = get_errors()
    try:
        import_ctf_util(backup)
    except Exception as e:
        print(e)
        errors.append(repr(e))

    if errors:
        return errors[0], 500
    else:
        return redirect(url_for("admin.config"))


@admin.route("/admin/export", methods=["GET", "POST"])
@admins_only
def export_ctf():
    backup = export_ctf_util()
    ctf_name = ctf_config.ctf_name()
    day = datetime.datetime.now().strftime("%Y-%m-%d")
    full_name = u"{}.{}.zip".format(ctf_name, day)
    return send_file(
        backup, cache_timeout=-1, as_attachment=True, attachment_filename=full_name
    )


@admin.route("/admin/export/csv")
@admins_only
def export_csv():
    table = request.args.get("table")

    # TODO: It might make sense to limit dumpable tables. Config could potentially leak sensitive information.
    model = get_class_by_tablename(table)
    if model is None:
        abort(404)

    temp = six.StringIO()
    writer = csv.writer(temp)

    header = [column.name for column in model.__mapper__.columns]
    writer.writerow(header)

    responses = model.query.all()

    for curr in responses:
        writer.writerow(
            [getattr(curr, column.name) for column in model.__mapper__.columns]
        )

    temp.seek(0)

    # In Python 3 send_file requires bytes
    output = six.BytesIO()
    output.write(temp.getvalue().encode("utf-8"))
    output.seek(0)
    temp.close()

    return send_file(
        output,
        as_attachment=True,
        cache_timeout=-1,
        attachment_filename="{name}-{table}.csv".format(
            name=ctf_config.ctf_name(), table=table
        ),
    )


@admin.route("/admin/config", methods=["GET", "POST"])
@admins_only
def config():
    # Clear the config cache so that we don't get stale values
    clear_config()

    database_tables = sorted(db.metadata.tables.keys())

    configs = Configs.query.all()
    configs = dict([(c.key, get_config(c.key)) for c in configs])

    themes = ctf_config.get_themes()
    themes.remove(get_config("ctf_theme"))

    return render_template(
        "admin/config.html", database_tables=database_tables, themes=themes, **configs
    )


@admin.route("/admin/reset", methods=["GET", "POST"])
@admins_only
def reset():
    if request.method == "POST":
        # Truncate Users, Teams, Submissions, Solves, Notifications, Awards, Unlocks, Tracking
        Tracking.query.delete()
        Solves.query.delete()
        Submissions.query.delete()
        Awards.query.delete()
        Unlocks.query.delete()
        Users.query.delete()
        Teams.query.delete()
        set_config("setup", False)
        db.session.commit()
        cache.clear()
        logout_user()
        db.session.close()
        return redirect(url_for("views.setup"))

    return render_template("admin/reset.html")

CTFd/auth.py
from flask import (
    current_app as app,
    render_template,
    request,
    redirect,
    url_for,
    session,
    Blueprint,
)
from itsdangerous.exc import BadTimeSignature, SignatureExpired, BadSignature

from CTFd.models import db, Users, Teams

from CTFd.utils import get_config, get_app_config
from CTFd.utils.decorators import ratelimit
from CTFd.utils import user as current_user
from CTFd.utils import config, validators
from CTFd.utils import email
from CTFd.utils.security.auth import login_user, logout_user
from CTFd.utils.crypto import verify_password
from CTFd.utils.logging import log
from CTFd.utils.decorators.visibility import check_registration_visibility
from CTFd.utils.config import is_teams_mode
from CTFd.utils.config.visibility import registration_visible
from CTFd.utils.modes import TEAMS_MODE
from CTFd.utils.security.signing import unserialize
from CTFd.utils.helpers import error_for, get_errors

import base64
import requests

auth = Blueprint("auth", __name__)


@auth.route("/confirm", methods=["POST", "GET"])
@auth.route("/confirm/<data>", methods=["GET"])
@ratelimit(method="POST", limit=10, interval=60)
def confirm(data=None):
    if not get_config("verify_emails"):
        # If the CTF doesn't care about confirming email addresses then redierct to challenges
        return redirect(url_for("challenges.listing"))

    # User is confirming email account
    if data and request.method == "GET":
        try:
            user_email = unserialize(data, max_age=1800)
        except (BadTimeSignature, SignatureExpired):
            return render_template(
                "confirm.html", errors=["Your confirmation link has expired"]
            )
        except (BadSignature, TypeError, base64.binascii.Error):
            return render_template(
                "confirm.html", errors=["Your confirmation token is invalid"]
            )

        user = Users.query.filter_by(email=user_email).first_or_404()
        user.verified = True
        log(
            "registrations",
            format="[{date}] {ip} - successful confirmation for {name}",
            name=user.name,
        )
        db.session.commit()
        db.session.close()
        if current_user.authed():
            return redirect(url_for("challenges.listing"))
        return redirect(url_for("auth.login"))

    # User is trying to start or restart the confirmation flow
    if not current_user.authed():
        return redirect(url_for("auth.login"))

    user = Users.query.filter_by(id=session["id"]).first_or_404()
    if user.verified:
        return redirect(url_for("views.settings"))

    if data is None:
        if request.method == "POST":
            # User wants to resend their confirmation email
            email.verify_email_address(user.email)
            log(
                "registrations",
                format="[{date}] {ip} - {name} initiated a confirmation email resend",
            )
            return render_template(
                "confirm.html",
                user=user,
                infos=["Your confirmation email has been resent!"],
            )
        elif request.method == "GET":
            # User has been directed to the confirm page
            return render_template("confirm.html", user=user)


@auth.route("/reset_password", methods=["POST", "GET"])
@auth.route("/reset_password/<data>", methods=["POST", "GET"])
@ratelimit(method="POST", limit=10, interval=60)
def reset_password(data=None):
    if data is not None:
        try:
            name = unserialize(data, max_age=1800)
        except (BadTimeSignature, SignatureExpired):
            return render_template(
                "reset_password.html", errors=["Your link has expired"]
            )
        except (BadSignature, TypeError, base64.binascii.Error):
            return render_template(
                "reset_password.html", errors=["Your reset token is invalid"]
            )

        if request.method == "GET":
            return render_template("reset_password.html", mode="set")
        if request.method == "POST":
            user = Users.query.filter_by(name=name).first_or_404()
            user.password = request.form["password"].strip()
            db.session.commit()
            log(
                "logins",
                format="[{date}] {ip} -  successful password reset for {name}",
                name=name,
            )
            db.session.close()
            return redirect(url_for("auth.login"))

    if request.method == "POST":
        email_address = request.form["email"].strip()
        team = Users.query.filter_by(email=email_address).first()

        get_errors()

        if config.can_send_mail() is False:
            return render_template(
                "reset_password.html",
                errors=["Email could not be sent due to server misconfiguration"],
            )

        if not team:
            return render_template(
                "reset_password.html",
                errors=[
                    "If that account exists you will receive an email, please check your inbox"
                ],
            )

        email.forgot_password(email_address, team.name)

        return render_template(
            "reset_password.html",
            errors=[
                "If that account exists you will receive an email, please check your inbox"
            ],
        )
    return render_template("reset_password.html")


@auth.route("/register", methods=["POST", "GET"])
@check_registration_visibility
@ratelimit(method="POST", limit=10, interval=5)
def register():
    errors = get_errors()
    if request.method == "POST":
        name = request.form["name"]
        email_address = request.form["email"]
        password = request.form["password"]

        name_len = len(name) == 0
        names = Users.query.add_columns("name", "id").filter_by(name=name).first()
        emails = (
            Users.query.add_columns("email", "id")
            .filter_by(email=email_address)
            .first()
        )
        pass_short = len(password) == 0
        pass_long = len(password) > 128
        valid_email = validators.validate_email(request.form["email"])
        team_name_email_check = validators.validate_email(name)

        if not valid_email:
            errors.append("Please enter a valid email address")
        if email.check_email_is_whitelisted(email_address) is False:
            errors.append(
                "Only email addresses under {domains} may register".format(
                    domains=get_config("domain_whitelist")
                )
            )
        if names:
            errors.append("That user name is already taken")
        if team_name_email_check is True:
            errors.append("Your user name cannot be an email address")
        if emails:
            errors.append("That email has already been used")
        if pass_short:
            errors.append("Pick a longer password")
        if pass_long:
            errors.append("Pick a shorter password")
        if name_len:
            errors.append("Pick a longer user name")

        if len(errors) > 0:
            return render_template(
                "register.html",
                errors=errors,
                name=request.form["name"],
                email=request.form["email"],
                password=request.form["password"],
            )
        else:
            with app.app_context():
                user = Users(
                    name=name.strip(),
                    email=email_address.lower(),
                    password=password.strip(),
                )
                db.session.add(user)
                db.session.commit()
                db.session.flush()

                login_user(user)

                if config.can_send_mail() and get_config(
                    "verify_emails"
                ):  # Confirming users is enabled and we can send email.
                    log(
                        "registrations",
                        format="[{date}] {ip} - {name} registered (UNCONFIRMED) with {email}",
                    )
                    email.verify_email_address(user.email)
                    db.session.close()
                    return redirect(url_for("auth.confirm"))
                else:  # Don't care about confirming users
                    if (
                        config.can_send_mail()
                    ):  # We want to notify the user that they have registered.
                        email.sendmail(
                            request.form["email"],
                            "You've successfully registered for {}".format(
                                get_config("ctf_name")
                            ),
                        )

        log("registrations", "[{date}] {ip} - {name} registered with {email}")
        db.session.close()

        if is_teams_mode():
            return redirect(url_for("teams.private"))

        return redirect(url_for("challenges.listing"))
    else:
        return render_template("register.html", errors=errors)


@auth.route("/login", methods=["POST", "GET"])
@ratelimit(method="POST", limit=10, interval=5)
def login():
    errors = get_errors()
    if request.method == "POST":
        name = request.form["name"]

        # Check if the user submitted an email address or a team name
        if validators.validate_email(name) is True:
            user = Users.query.filter_by(email=name).first()
        else:
            user = Users.query.filter_by(name=name).first()

        if user:
            if user and verify_password(request.form["password"], user.password):
                session.regenerate()

                login_user(user)
                log("logins", "[{date}] {ip} - {name} logged in")

                db.session.close()
                if request.args.get("next") and validators.is_safe_url(
                    request.args.get("next")
                ):

CTFd/themes/ctfhub/templates/base.html
<!DOCTYPE html>
<html class="loading" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <title>{{ get_ctf_name() }}</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i%7COpen+Sans:300,300i,400,400i,600,600i,700,700i" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ url_for('views.themes', path='assets/css/vendors.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('views.themes', path='assets/vendors/css/charts/jquery-jvectormap-2.0.3.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('views.themes', path='assets/css/app.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('views.themes', path='assets/css/core/menu/horizontal-menu.min.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ url_for('views.themes', path='assets/css/style.css') }}">
	<script src="{{ url_for('views.themes', path='js/vendor/nunjucks.min.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/vendor/moment.min.js') }}"></script>
	<link rel="stylesheet" type="text/css" href="{{ url_for('views.themes', path='assets/fonts/font-awesome/css/font-awesome.min.css') }}">
	{% block stylesheets %}{% endblock %}
	{% for stylesheet in get_registered_stylesheets() %}
		{% if stylesheet.startswith('http') %}
			<link rel="stylesheet" type="text/css" href="{{ stylesheet }}">
		{% elif request.script_root %}
			<link rel="stylesheet" type="text/css" href="{{ request.script_root }}/{{ stylesheet }}">
		{% else %}
			<link rel="stylesheet" type="text/css" href="{{ stylesheet }}">
		{% endif %}
	{% endfor %}
	<script src="{{ url_for('views.themes', path='js/CTFd.js') }}"></script>
	<script type="text/javascript">
		var script_root = "{{ request.script_root }}";
		var csrf_nonce = "{{ nonce }}";
		var user_mode = "{{ get_config('user_mode') }}";
		var ctf_start = {{ get_config("start") | tojson }};
		var ctf_end = {{ get_config("end") | tojson }};
		CTFd.options.urlRoot = script_root;
		CTFd.options.csrfNonce = csrf_nonce;
		CTFd.options.start = ctf_start;
		CTFd.options.end = ctf_end;
	</script>
  </head>
  <body class="horizontal-layout horizontal-menu 2-columns menu-expanded" data-open="click" data-menu="horizontal-menu" data-col="2-columns">
    <nav class="header-navbar navbar-expand-md navbar navbar-with-menu navbar-static-top navbar-light navbar-border navbar-brand-center">
      <div class="navbar-wrapper">
        <div class="navbar-header">
          <ul class="nav navbar-nav flex-row">
			<li class="nav-item mobile-menu d-md-none mr-auto"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ft-menu font-large-1"></i></a></li>
			{% if get_ctf_logo() %}
			<li class="nav-item"><a class="navbar-brand" href="{{ url_for('views.static_html', route='/') }}"><img class="brand-logo" alt="ctfhub logo" src="{{ url_for('views.files', path=get_ctf_logo()) }}"><h2 class="brand-text">{{ get_ctf_name() }}</h2></a></li>
				{% else %}
				<li class="nav-item"><a class="navbar-brand" href="{{ url_for('views.static_html', route='/') }}"><h2 class="brand-text">{{ get_ctf_name() }}</h2></a></li>
			{% endif %}
            <li class="nav-item d-md-none"><a class="nav-link open-navbar-container" data-toggle="collapse" data-target="#navbar-mobile"><i class="fa fa-ellipsis-v"></i></a></li>
          </ul>
        </div>
        <div class="navbar-container container center-layout">
          <div class="collapse navbar-collapse" id="navbar-mobile">
            <ul class="nav navbar-nav mr-auto float-left">
              <li class="nav-item d-none d-md-block"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ft-menu"></i></a></li>
            </ul>
            <ul class="nav navbar-nav float-right">
			{% if name is defined %}
              <li class="dropdown dropdown-user nav-item"><a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown"><span class="user-name">{{ name }}</span></a>
                <form id="logout" method="post" action="logout" style="display: none;"></form>
				<div class="dropdown-menu dropdown-menu-right">
					{% if type == 'admin' %}
						<a class="dropdown-item" href="{{ url_for('admin.view') }}"><i class="ft-activity"></i> Admin</a>
					{% endif %}
					{% if config.user_mode() == "teams" %}
						<a class="dropdown-item" href="{{ url_for('teams.private') }}"><i class="ft-users"></i> Team</a>
					{% endif %}
					<!--<a class="dropdown-item" href="{{ url_for('users.private') }}"><i class="ft-user"></i> Profile</a>-->
					<a class="dropdown-item" href="{{ url_for('views.settings') }}"><i class="ft-settings"></i> Settings</a>
					<a class="dropdown-item" href="{{ url_for('auth.logout') }}"><i class="ft-power"></i> Logout</a>
				</div>
			  </li>
			  {% else %}
				{% if registration_visible() %}
					<li class="nav-item">
						<a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
					</li>
					<li class="nav-item">
						<a class="nav-link d-none d-md-block d-lg-block">|</a>
					</li>
				{% endif %}
				<li class="nav-item">
					<a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
				</li>
			  {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </nav>
    <div class="header-navbar navbar-expand-sm navbar navbar-horizontal navbar-fixed navbar-light navbar-without-dd-arrow navbar-shadow menu-border" role="navigation" data-menu="menu-wrapper">
      <div class="navbar-container main-menu-content container center-layout" data-menu="menu-container">
        <ul class="nav navbar-nav" id="main-menu-navigation" data-menu="menu-navigation">
		  {% for page in get_user_page_menu_bar() %}
		  {% if page.route.startswith('http://') or page.route.startswith('https://') %}
     		<li class="nav-item"><a class="nav-link" href="{{ page.route }}"><i class="ft-home"></i><span>{{ page.title }}</span></a></li>
		  {% else %}
		    <li class="nav-item"><a class="nav-link" href="{{ url_for('views.static_html', route=page.route) }}"><i class="ft-home"></i><span>{{ page.title }}</span></a></li>
		  {% endif %}
		  {% endfor %}
		  <li class="nav-item"><a class="nav-link" href="{{ url_for('views.static_html', route='/') }}"><i class="ft-home"></i><span>Home</span></a></li>
		  <li class="nav-item"><a class="nav-link" href="{{ url_for('views.notifications') }}"><i class="ft-file-text"></i><span>Notifications</span></a></li>
		  <!--{% if get_config('account_visibility') != 'admins' %}
		    <li class="nav-item"><a class="nav-link" href="{{ url_for('users.listing') }}"><i class="ft-users"></i><span>Users</span></a></li>
			{% if get_config('user_mode') == 'teams' %}
			<li class="nav-item"><a class="nav-link" href="{{ url_for('teams.listing') }}"><i class="ft-users"></i><span>Teams</span></a></li>
		  	{% endif %}
		  {% endif %}-->
		  {% if get_config('score_visibility') != 'admins' %}
		    <li class="nav-item"><a class="nav-link" href="{{ url_for('scoreboard.listing') }}"><i class="ft-award"></i><span>Leaderboard</span></a></li>
		  {% endif %}
		  <li class="nav-item"><a class="nav-link" href="{{ url_for('challenges.listing') }}"><i class="fa fa-bolt"></i><span>Challenges</span></a></li>
        </ul>
      </div>
    </div>
    <div class="app-content container center-layout mt-2">
      <div class="content-wrapper">
        <div class="content-header row"></div>
        <div class="content-body">
				{% block content %}
				{% endblock %}
        </div>
      </div>
    </div>
    <footer class="footer footer-static footer-light navbar-shadow fixed-bottom">
      <p class="clearfix blue-grey lighten-2 text-sm-center mb-0 px-2 container center-layout"><span class="float-md-left d-block d-md-inline-block">Copyright © 2019. </span><span class="float-md-right d-block d-md-inline-block d-none d-lg-block">Made with <i class="ft-heart pink"></i> and ton of code</span></p>
    </footer>
    <script src="{{ url_for('views.themes', path='assets/vendors/js/vendors.min.js') }}" type="text/javascript"></script>
    <script type="text/javascript" src="{{ url_for('views.themes', path='assets/vendors/js/ui/jquery.sticky.js') }}"></script>
    <script src="{{ url_for('views.themes', path='assets/js/core/app-menu.js') }}" type="text/javascript"></script>
	<script src="{{ url_for('views.themes', path='assets/js/core/app.js') }}" type="text/javascript"></script>
	<script src="{{ url_for('views.themes', path='js/vendor/markdown-it.min.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/utils.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/ezq.js') }}"></script>

	{% for script in get_registered_scripts() %}
	{% if script.startswith('http') %}
	<script src="{{ script }}"></script>
	{% elif request.script_root %}
	<script src="{{ request.script_root }}/{{ script }}"></script>
	{% else %}
	<script src="{{ script }}"></script>
	{% endif %}
	{% endfor %}
	{% block scripts %}
	{% endblock %}
  </body>
</html>

CTFd/themes/ctfhub/templates/chall-base.html
{% extends "base.html" %}

{% block stylesheets %}
	<link rel="stylesheet" href="{{ url_for('views.themes', path='css/challenge-board.css') }}">
{% endblock %}

{% block content %}
<div class="col-12 pt-2">
	<div class="pointcard overflow-hidden">
	  <div class="card-content">
		  <div class="media align-items-stretch">
			<div class="media-body">
				<div class="float-left pl-2">
					<span class="font-large-3 text-bold-300">Challenges</span>
				</div>
			</div>
		  </div>
	  </div>
	</div>
</div>
{% if infos %}
	<div class="container">
		<div id='errors' class="row">
			<div class="col-md-12">
				{% for info in infos %}
					<h1 class="text-center">{{ info }}</h1>
				{% endfor %}
			</div>
		</div>
	</div>
{% endif %}

{% if errors %}
<div class="container">
	<div id='errors' class="row">
		<div class="col-md-12">
{% for error in errors %}
			<h1 class="text-center">{{ error }}</h1>
{% endfor %}
		</div>
	</div>
</div>
{% endif %}

{% if admin or not errors %}
<div class="container">
	<div id='challenges-board'>
		<div class="text-center">
			<i class="fas fa-circle-notch fa-spin fa-3x fa-fw spinner"></i>
		</div>
	</div>
</div>

<input id="nonce" type="hidden" name="nonce" value="{{ nonce }}">

<div class="modal fade" id="challenge-window" tabindex="-1" role="dialog">
</div>
{% endif %}
<div class="pb-4">

</div>
{% endblock %}

{% block scripts %}
	<script>
		var authed = {{ (id is defined) | tojson }};
	</script>
	<script src="{{ url_for('views.themes', path='js/utils.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/multi-modal.js') }}"></script>
	{% if admin or not errors %}
	<script src="{{ url_for('views.themes', path='js/challenges.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/hints.js') }}"></script>
	{% endif %}
	<script src="{{ url_for('views.themes', path='js/style.js') }}"></script>
{% endblock %}

CTFd/themes/ctfhub/templates/login.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>HackerEarth - LOGIN</title>
        <link href="/favicon.png" rel="icon" type="image/png">

        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{{ url_for('views.themes', path='assets/fonts/font-awesome/css/font-awesome.min.css') }}">
        <link type="text/css" href="{{ url_for('views.themes', path='assets/css/auth.css') }}" rel="stylesheet">
    </head>
    <body class="bg-default">
        <div class="main-content">
    <div class="header bg-gradient-primary py-7 py-lg-8">
        <div class="container">
            <div class="header-body text-center mb-7">
                <div class="row justify-content-center">
                    <div class="col-lg-5 col-md-6">
                        <h1 class="text-white">Welcome to HackerEarth</h1>
                        <p class="text-lead text-light">
                            Login and start solving some challenges.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="separator separator-bottom separator-skew zindex-100">
            <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1"
                 xmlns="http://www.w3.org/2000/svg">
                <polygon class="fill-default" points="2560 0 2560 100 0 100"></polygon>
            </svg>
        </div>
    </div>
    <div class="container mt--8 pb-5">
        <div class="row justify-content-center">
            <div class="col-lg-5 col-md-7">
                <div class="card bg-secondary shadow border-0">
                    <div class="card-body px-lg-5 py-lg-5">
                        <form method="post" accept-charset="utf-8" autocomplete="off" role="form" class="form-horizontal">

                            <div class="form-group mb-3">
                                <div class="input-group input-group-alternative">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fa fa-user"></i></span>
                                    </div>
                                    <input class="form-control" placeholder="E-mail or username" type="text"
                                           name="name" required autofocus>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group input-group-alternative">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fa fa-lock"></i></span>
                                    </div>
                                    <input class="form-control" name="password" placeholder="Enter your password"
                                           type="password" required>
                                </div>
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary my-4">Login</button>
							</div>
							<input type="hidden" name="nonce" value="{{ nonce }}">
                        </form>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-6">
                            <!--<a href="{{ url_for('auth.reset_password') }}" class="text-light">
                                <small>Forgot password?</small>
                            </a>-->
                    </div>
                    <div class="col-6 text-right">
                        <a href="{{ url_for('auth.register') }}" class="text-light">
                            <small>Create new account</small>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

        </div>
    </body>
</html>

CTFd/themes/ctfhub/templates/page.html
{% extends "base.html" %}

{% block content %}
	<div class="container">
	{{ content | safe }}
	</div>
{% endblock %}